micronaut:
  application:
    name: kafkaProtobufContainerTest
kafka:
  enabled: true
  schema.registry.url: http://localhost:8081
  key:
    serializer: org.apache.kafka.common.serialization.UUIDSerializer
    deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
  specific:
    protobuf:
      value:
        type: com.krickert.search.model.DemoDocument
  value:
    serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
    schema:
      canonicalize:
        on:
          consume: PROTOBUF
